In [ ]:
import torch

In [ ]:
# Tensor is a multidimensional array.
x=torch.Tensor([5,3])
y=torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [ ]:
x=torch.zeros([2,5])

In [ ]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [ ]:
x.shape

torch.Size([2, 5])

In [ ]:
y=torch.rand([2,5])

In [ ]:
print(y)

tensor([[0.3646, 0.6519, 0.8712, 0.6901, 0.7489],
        [0.8642, 0.3932, 0.2033, 0.9477, 0.5583]])


In [ ]:
# Reshape -- Example: Flatten operation
y=y.view([1,10])
print(y)

tensor([[0.3646, 0.6519, 0.8712, 0.6901, 0.7489, 0.8642, 0.3932, 0.2033, 0.9477,
         0.5583]])
